version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      # Override auto-detection to ensure we use the real model with GPU
      - AI_FALLBACK_MODE=false
      - MISTRAL_API_URL=http://ai-service:80
    depends_on:
      - ai-service

  # Real AI service with GPU support
  ai-service:
    image: ghcr.io/huggingface/text-generation-inference:1.1.0
    ports:
      - "8080:80"
    volumes:
      - ai-model-data:/data
    environment:
      - MODEL_ID=teknium/OpenHermes-2.5-Mistral-7B
      - QUANTIZE=q4_k_m
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=8192
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ai-model-data:
