version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - AI_FALLBACK_MODE=true
      - MISTRAL_API_URL=http://ai-service:80

  # AI service commented out - requires GPU with flash attention v2
  # Uncomment and configure when GPU hardware is available
  # ai-service:
  #   image: ghcr.io/huggingface/text-generation-inference:1.1.0
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ai-model-data:/data
  #   environment:
  #     - MODEL_ID=teknium/OpenHermes-2.5-Mistral-7B
  #     - QUANTIZE=bitsandbytes
  #     - MAX_INPUT_LENGTH=4096
  #     - MAX_TOTAL_TOKENS=8192
  #     - USE_CUDA=true

volumes:
  ai-model-data:
