version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ai-service

  ai-service:
    image: ghcr.io/huggingface/text-generation-inference:1.1.0
    ports:
      - "8080:80"
    volumes:
      - ai-model-data:/data
    environment:
      - MODEL_ID=teknium/OpenHermes-2.5-Mistral-7B
      - QUANTIZE=q4_k_m
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=8192
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ai-model-data:
