version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      # AI_FALLBACK_MODE is auto-detected based on GPU availability
      # You can override it by uncommenting the line below
      # - AI_FALLBACK_MODE=false  # Set to false when GPU is available
      - MISTRAL_API_URL=http://ai-service:80

  # AI service configuration
  # This will use GPU if available, otherwise it will run in CPU mode
  ai-service:
    image: ghcr.io/huggingface/text-generation-inference:1.1.0
    ports:
      - "8080:80"
    volumes:
      - ai-model-data:/data
    environment:
      - MODEL_ID=teknium/OpenHermes-2.5-Mistral-7B
      - QUANTIZE=q4_k_m
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=8192
    # GPU configuration - will be used if available
    # If GPU is not available, this will be ignored and the service will run in CPU mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              options:
                # Make GPU requirement optional
                driver.capabilities: utility,compute,video
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ai-model-data:
