services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - AI_FALLBACK_MODE=false

  ai-service:
    image: ghcr.io/huggingface/text-generation-inference:1.1.0
    ports:
      - "8080:80"
    volumes:
      - ai-model-data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - MODEL_ID=teknium/OpenHermes-2.5-Mistral-7B
      - QUANTIZE=q4_k_m
      - MAX_INPUT_LENGTH=4096
      - MAX_TOTAL_TOKENS=8192
      - USE_CUDA=true
      - CUDA_VISIBLE_DEVICES=0  # usa tu primera GPU

volumes:
  ai-model-data:
