[build]
  command = "pip install poetry && poetry install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
